version: '3.8'

services:
  dmw-tracker:
    image: nginx:alpine
    container_name: dmw_tracker_app
    restart: unless-stopped
    ports:
      - "8082:80" # Acede via http://IP-DO-SERVER:8081
    volumes:
      # Mapeia a tua pasta atual para dentro do Nginx.
      # Isto permite que edites no VS Code e vejas as alterações logo no browser (F5)
      - ./src:/usr/share/nginx/html
    networks:
      - dmw_net

networks:
  dmw_net:
    driver: bridge